[package]
name = "checkme"
version = "0.1.0"
edition = "2021"
authors = ["Elad-Kaplan <kaplan.elad@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/kaplanelad/checkme"
homepage = "https://github.com/kaplanelad/checkme"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
